### PR TITLE
Crowdplatform db fix

### PR DESCRIPTION
**Pull request by marcelhollerbach**
We have to keep the database consistent, for the case a platform disappears in our installation we need to mark this platform somehow as dead. So we can keep our database halfway consistent.

### CODE REVIEW

**Comment by marcelhollerbach** [comment]
We need a additional field in platforms-table where we can store the "lock" bit which marks a database as dead.

**Comment by LeanderK** [comment]
what is the expected behaviour of the /platforms call? Does it include the inactive platforms?

**Comment by marcelhollerbach** [comment]
added the docs for it ... sorry I forgot them.

**Comment by LeanderK** [comment]
I'll reopen it when i'm finished

**Comment by LeanderK** [comment]
i meant the rest GET /platforms call, inactive is currently to my knowledge not defined in the protobufs, so should i filter them out?

**Comment by marcelhollerbach** [comment]
oh good question @kelunik what do you mean?

**Comment by kelunik** [comment]
What are the implications of a `dead` platform?

**Comment by marcelhollerbach** [comment]
platform which is not configured anymore...

**Comment by kelunik** [comment]
If we still want to show them in old experiments which used those platforms, we have to expose them in `GET /platforms` and add the inactive flag to the proto spec.

**Comment by marcelhollerbach** [comment]
yeah, thats the point, what do you want?

**Comment by kelunik** [comment]
Exposing them with an inactive flag is fine.

**Comment by marcelhollerbach** [comment]
Can you add them to proto ?

**Comment by kelunik** [comment]
Done via https://github.com/coolcrowd/object-service/pull/100.

**Pull request closed without merging**
