### PR TITLE
Add experiment integration tests

### PR DESCRIPTION
**Pull request by kelunik**
Tests are skipped locally for a unknown reason: https://gist.github.com/kelunik/36d624f8ef7db53bbe6a

I can't test this locally, so either somebody else has to test it or it has to wait until `restTest` is enabled on Travis again.

@LeanderK

### CODE REVIEW

**Comment by marcelhollerbach** [comment]
rebase please.

**Comment by kelunik** [comment]
Please rebase, don't have my Notebook right now.

**Comment by kelunik** [comment]
Don't merge yet!

**Comment by kelunik** [comment]
Fixes also binary handling for `application/protobuf` and deletion of experiments. @LeanderK

**Comment by LeanderK** [comment]
i just wanted to ask whether i can migrate to protobuf ;)

**Comment by kelunik** [comment]
Tests were using `application/protobuf` the whole time, it just failed for experiments, because the payload is probably encoded differently, because more fields. And `String` does always need a charset, so we switch instead to sending a raw response.

**Comment by kelunik** [comment]
Ready to merge now.

We really need to reenable `restTest` on Travis.

**Comment by kelunik** [comment]
`restTest` is now enabled again and running against MySQL 5.7. We're running on GCE now.

Also disabled SSL.

It's fine now. @marcelhollerbach

**Pull request merged**
