### PR TITLE
Quality2

### PR DESCRIPTION
**Pull request by lckr**
- Quality-package 
- Payment-package
- (autoformat of everything)

### CODE REVIEW

**Comment by LeanderK** [comment]
this is going to be ugly -.-

**Comment by LeanderK** [comment]
ok, this is not going to work....can you revert the auto-format commit? Reviewing 219 files is not funny. You can do an auto format in another branch. 
Also nice try: https://github.com/coolcrowd/object-service/blob/quality2/src/main/java/edu/kit/ipd/crowdcontrol/objectservice/database/operations/AnswerRatingOperations.java#L21

**Comment by kelunik** [comment]
https://github.com/coolcrowd/object-service/pull/59/files?w=0

Autoformat is a bad idea.

**Comment by marcelhollerbach** [comment]
Just in general a pull request requests one context to get merged. This one wants to merge two context and one useless purpose, please close and try again

**Pull request closed without merging**
