### PR TITLE
Support task modes for populations

### PR DESCRIPTION
**Pull request by kelunik**
**WIP**
- [x] Update spec

**TODO** @LeanderK 
- [x] Store information in `storePopulations`
- [x] Store information in `updateExperimentStopgap` which doesn't use `storePopulations`
- [x] Expose information in `GET`

### CODE REVIEW

**Comment by LeanderK** [comment]
i worked on the wrong branch, and then i forgot to commit...and then rebased, aborted and don't now where my progress is. I feel stupid now and will start again tomorrow.

**Comment by LeanderK** [comment]
push @kelunik ....wait a bit, found an error

**Comment by LeanderK** [comment]
resolved

**Comment by marcelhollerbach** [comment]
pls rebase

**Pull request merged**
