### PR TITLE
database: fixed bug

### PR DESCRIPTION
**Pull request by LeanderK**
- time was in milliseconds and promo expected seconds

### CODE REVIEW

**Comment by LeanderK** [comment]
@marcelhollerbach noted that milliseconds worked when he tested it. @kelunik is it possible that the specification is wrong and you use milliseconds too?

**Comment by kelunik** [comment]
It's a bug in both implementations, not the spec. ;-)

**Comment by LeanderK** [comment]
so what gets altered? the implementation or the spec? If its a bug you can merge the pull request ;)

**Comment by kelunik** [comment]
Implementations. ;-)

**Pull request merged**
