### PR TITLE
Proto

### PR DESCRIPTION
**Pull request by LeanderK**
updated the photo-files. The Rating in Rating is now boxed, because ratings of 0 should be allowed.

### CODE REVIEW

**Comment by LeanderK** [comment]
don't merge, we have to wait for the ws for this one

**Comment by kelunik** [comment]
We don't need boxing to allow 0 values. We just need it where we have to update another value to a value being 0.

**Comment by LeanderK** [comment]
well, it will fix #178

**Comment by kelunik** [comment]
Removing the assertion here: https://github.com/coolcrowd/object-service/blob/proto/src/main/java/edu/kit/ipd/crowdcontrol/objectservice/database/operations/AnswerRatingOperations.java#L267 also fixes it without any BC impact.

**Comment by LeanderK** [comment]
ok, maybe i had not put enough thought in it ;)

**Pull request closed without merging**
