### PR TITLE
Fix workerIdentfication to not call identifyWorker() more than once

### PR DESCRIPTION
**Pull request by simonkorz**
Fix workerIdentfication to not call identifyWorker() more than once per request, as there are platforms that might not be able to identify a worker for given parameters more than once.

### CODE REVIEW

**Comment by LeanderK** [comment]
this is not how it works....or how it was designed to work. What exactly is your problem?

**Comment by LeanderK** [comment]
also we don't want to rely on string identification. this will change to make things easier (amazon was blocking). Please write me a message, since the functionality was kinda constrained by the db, which will hopefully improve in the qs-phase

**Comment by simonkorz** [comment]
The underlying problem is that the identification part of the pybossa implementation can only identify a worker for given params once (because we need to clear the used identification task to make it reusable). So my intent was to change the usage of the identifyWorker interface to call identify only once, as this came with least changes to other parts.

**Comment by kelunik** [comment]
Identify must be idempotent, so it must be possible to call it how often you want and it must not have any side effects.

**Pull request closed without merging**
