### PR TITLE
Make empty lists return 200 instead of 404

### PR DESCRIPTION
**Pull request by kelunik**

### CODE REVIEW

**Comment by LeanderK** [comment]
why does it return 202 instead of 404 now?

**Comment by LeanderK** [comment]
it would be cool if you could wait for me if you change my code

**Comment by kelunik** [comment]
Anything wrong with it?

**Comment by LeanderK** [comment]
no, but there might be, also it's code in my package and i'd like to keep the control over it. Its not easy (especially in the database package) to keep track of all the changes been introduced all the the time.

**Pull request merged**
